### ISSUE TITLE
Feature: Revise users section to be for non-admin users

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/prism-docs#46]
### Is your feature request related to a problem? Please describe.

users page is only accessible to admins

### Describe the feature you are requesting, as well as the possible use case(s) for it.

limit this section parts of ui accessible to all users

### Indicate the importance of this feature to you.

Must-have

**Comment by WashingtonKK** [comment]
@SammyOina Users section is not accessible to non-admin users and therefore this section has to be for admin users.
